version: "3"
services:
  node0:
    build:
      context: .
      dockerfile: NodeDockerfile
    # image: chordnode
    # container_name: chordnode
    command: npm run devServer -- --ip node0 --id 0 --targetIp node0 --targetPort 1337 --targetId 0
  node1:
    build:
      context: .
      dockerfile: NodeDockerfile
    # image: chordnode
    # container_name: chordnode
    command: npm run devServer -- --ip node1 --id 6 --targetIp node0 --targetPort 1337 --targetId 0
    depends_on:
      - node0
  node2:
    build:
      context: .
      dockerfile: NodeDockerfile
    # image: chordnode
    # container_name: chordnode
    command: npm run devServer -- --ip node2 --id 1 --targetIp node0 --targetPort 1337 --targetId 0
    depends_on:
      - node0
  node3:
    build:
      context: .
      dockerfile: NodeDockerfile
    # image: chordnode
    # container_name: chordnode
    command: npm run devServer -- --ip node3 --id 2 --targetIp node0 --targetPort 1337 --targetId 0
    depends_on:
      - node0
  node4:
    build:
      context: .
      dockerfile: NodeDockerfile
    # image: chordnode
    # container_name: chordnode
    command: npm run devServer -- --ip node4 --id 3 --targetIp node0 --targetPort 1337 --targetId 0
    depends_on:
      - node0
  node5:
    build:
      context: .
      dockerfile: NodeDockerfile
    # image: chordnode
    # container_name: chordnode
    command: npm run devServer -- --ip node5 --id 7 --targetIp node0 --targetPort 1337 --targetId 0
    depends_on:
      - node0
  client:
    build:
      context: .
      dockerfile: ClientDockerfile
    # image: chordclient
    # container_name: chordclient
    ports:
      - "1337:1337"
    depends_on:
      - node0
    # volumes:
    #   - .:/home/node/app
    #   - /home/node/app/node_modules/
    command: npm run devClient -- crawl --ip node0 --port 1337 --webPort 1337
